---
- name: Generate systemd unit with create command
  become: true
  command: "{{ kolla_container_engine }} generate systemd --name {{ service }} --files --new"
  args:
    chdir: /etc/systemd/system
  register: podman_generate
  failed_when: podman_generate.rc not in [0, 125]
  changed_when: podman_generate.rc == 0
  notify: Reload systemd

- name: Generate systemd unit without create command
  become: true
  command: "{{ kolla_container_engine }} generate systemd --name {{ service }} --files"
  args:
    chdir: /etc/systemd/system
  when: podman_generate.rc == 125
  register: podman_generate_fallback
  changed_when: podman_generate_fallback.rc == 0
  notify: Reload systemd

- name: Fail if systemd unit generation failed
  when: podman_generate.rc not in [0, 125] or (podman_generate.rc == 125 and podman_generate_fallback.rc != 0)
  fail:
    msg: "podman generate systemd failed for {{ service }}"
