---
# Default start priority for compute node services
kolla_service_unit_prefix: "{{ 'container-' if kolla_container_engine == 'podman' else 'kolla-' }}"
kolla_service_unit_suffix: "{{ '' if kolla_container_engine == 'podman' else '-container' }}"
kolla_service_start_priority:
  - kolla_toolbox
  - openvswitch_db
  - openvswitch_vswitchd
  - neutron_ovs_cleanup
  - neutron_openvswitch_agent
  - nova_libvirt
  - nova_ssh
  - nova_compute
  - ceilometer_compute
  - collectd

# Containers recreated during the playbook run and started directly via
# ``podman start``. These are restarted under systemd exactly once when the
# ``service-start-order`` role executes.
kolla_changed_containers: []

#####################
# Service start wait behaviour
#####################
# Timeout applied to systemd services while waiting for dependency health.
# Set to 0 to disable the timeout.
kolla_service_start_timeout: 0
# Delay applied when a dependency has no container healthcheck.
kolla_service_no_healthcheck_wait: 30
# Attempts and delay for verifying container health after restart/start
kolla_service_healthcheck_retries: 60
kolla_service_healthcheck_delay: 2

#####################
# OVS cleanup
#####################
# Marker file used to ensure neutron_ovs_cleanup runs only once per boot.
# A dedicated directory prevents conflicts with the cleanup script which is
# copied to ``/tmp/kolla/neutron_ovs_cleanup`` inside the container.
neutron_ovs_cleanup_marker_file: "/tmp/kolla/neutron_ovs_cleanup_marker/done"

#####################
# One-shot services
#####################
# Mapping of services which execute only once per host boot and should not be
# restarted or waited on after completion. Each entry may define a marker file
# indicating that the service has already run.
kolla_service_one_shot:
  neutron_ovs_cleanup:
    marker: "{{ neutron_ovs_cleanup_marker_file }}"
