---
# Default start priority for compute node services
kolla_service_unit_prefix: "{{ 'container-' if kolla_container_engine == 'podman' else 'kolla-' }}"
kolla_service_unit_suffix: "{{ '' if kolla_container_engine == 'podman' else '-container' }}"
kolla_service_start_wait_seconds: 45
kolla_service_start_priority:
  - kolla_toolbox
  - openvswitch_db
  - openvswitch_vswitchd
  - neutron_ovs_cleanup
  - neutron_openvswitch_agent
  - nova_libvirt
  - nova_ssh
  - nova_compute
  - ceilometer_compute
  - collectd

#####################
# OVS cleanup
#####################
# Marker file used to ensure neutron_ovs_cleanup runs only once per boot
neutron_ovs_cleanup_marker_file: "/tmp/kolla/neutron_ovs_cleanup/done"
