---
# Default start priority for compute node services
kolla_service_unit_prefix: "{{ 'container-' if kolla_container_engine == 'podman' else 'kolla-' }}"
kolla_service_unit_suffix: "{{ '' if kolla_container_engine == 'podman' else '-container' }}"
kolla_service_start_priority:
  - kolla_toolbox
  - openvswitch_db
  - openvswitch_vswitchd
  - neutron_ovs_cleanup
  - neutron_openvswitch_agent
  - nova_libvirt
  - nova_ssh
  - nova_compute
  - ceilometer_compute
  - collectd

#####################
# Service start wait behaviour
#####################
# Timeout applied to systemd services while waiting for dependency health.
# Set to 0 to disable the timeout.
kolla_service_start_timeout: 0
# Delay applied when a dependency has no container healthcheck.
kolla_service_no_healthcheck_wait: 30

#####################
# OVS cleanup
#####################
# Marker file used to ensure neutron_ovs_cleanup runs only once per boot
neutron_ovs_cleanup_marker_file: "/tmp/kolla/neutron_ovs_cleanup/done"
