---
# Generate systemd unit files for Neutron containers when using Podman
- name: Generate Podman systemd units for Neutron
  include_role:
    name: common
    tasks_from: podman_systemd
  vars:
    service: "{{ item.value }}"
  loop: "{{ neutron_services | select_services_enabled_and_mapped_to_host | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

