---
- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read drop-in for neutron_openvswitch_agent
      become: true
      slurp:
        path: /etc/systemd/system/container-neutron_openvswitch_agent.service.d/start-order.conf
      register: dropin

    - name: Assert drop-in references openvswitch_vswitchd
      vars:
        content: "{{ dropin.content | b64decode }}"
      assert:
        that:
          - "'After=container-openvswitch_vswitchd.service' in content"
          - "'Requires=container-openvswitch_vswitchd.service' in content"
