---
- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read start order drop-ins
      become: true
      slurp:
        path: "{{ item }}"
      loop:
        - /etc/systemd/system/container-c2.service.d/start-order.conf
        - /etc/systemd/system/kolla-c2-container.service.d/start-order.conf
      register: dropins

    - name: Assert drop-ins contain wait logic
      vars:
        contents: "{{ dropins.results | map(attribute='content') | map('b64decode') | list }}"
      assert:
        that:
          - "'After=container-c1.service' in contents[0]"
          - "'Requires=container-c1.service' in contents[0]"
          - "'TimeoutStartSec=0' in contents[0]"
          - "'ExecStartPre=/bin/sh -c' in contents[0]"
          - "'systemctl is-active --quiet container-c1.service' in contents[0]"
          - "'podman healthcheck run c1' in contents[0]"
          - "'sleep 30' in contents[0]"
          - "'sleep 5' in contents[0]"
          - contents[0] == contents[1]

    - name: Read recorded start times
      become: true
      slurp:
        path: /tmp/start_times.json
      register: start_file

    - name: Set start times fact
      set_fact:
        start_before: "{{ start_file.content | b64decode | from_json }}"

    - name: Get c1 start time after
      command: >-
        podman inspect c1 --format '{% raw %}{{.State.StartedAt}}{% endraw %}'
      register: c1_after
      changed_when: false

    - name: Get c2 start time after
      command: >-
        podman inspect c2 --format '{% raw %}{{.State.StartedAt}}{% endraw %}'
      register: c2_after
      changed_when: false

    - name: Ensure c1 now managed by systemd
      command: systemctl is-active --quiet container-c1.service
      register: c1_active
      failed_when: c1_active.rc != 0

    - name: Assert start times
      assert:
        that:
          - c1_after.stdout != start_before.c1
          - c2_after.stdout != start_before.c2
