---
- name: Debug processing group
  debug:
    msg: "Processing secrets for group {{ group }}"
- name: Ensure destination directory exists
  become: true
  file:
    path: "{{ kolla_secrets_dest }}/{{ group }}"
    state: directory
    mode: '0700'
- name: Copy secret files for group
  become: true
  copy:
    src: "{{ item.path }}"
    dest: "{{ kolla_secrets_dest }}/{{ group }}/{{ item.path | basename }}"
    owner: root
    group: root
    mode: >-
      {% set filename = item.path | basename %}
      {% if filename == 'known_hosts' or filename.endswith('.pub') %}
      0644
      {% elif filename | regex_search('.*(_rsa|_dsa|_ed25519|_ecdsa|_key)$') %}
      0600
      {% else %}
      {{ item.mode if (item.mode | int(base=8)) <= 420 else '0644' }}
      {% endif %}
  loop: "{{ kolla_secret_files.get(group, []) }}"
  loop_control:
    label: "{{ item.path | basename }}"
- name: Debug copied files
  debug:
    msg: "Copied {{ kolla_secret_files.get(group, []) | length }} files for group {{ group }}"
