---
- name: Debug processing group
  debug:
    msg: "Processing secrets for group {{ group }}"
- name: Ensure destination directory exists
  become: true
  file:
    path: "{{ kolla_secrets_dest }}/{{ group }}"
    state: directory
    mode: '0700'
- name: Copy secret files for group
  become: true
  copy:
    src: "{{ item.path }}"
    dest: "{{ kolla_secrets_dest }}/{{ group }}/{{ item.path | basename }}"
    owner: root
    group: root
    mode: "{{ item.mode if (item.mode | int(base=8)) <= 420 else '0644' }}"
  loop: "{{ kolla_secret_files[group] }}"
  loop_control:
    label: "{{ item.path | basename }}"
- name: Debug copied files
  debug:
    msg: "Copied {{ kolla_secret_files[group] | length }} files for group {{ group }}"
