---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    openvswitch_db_ready_timeout: 45
  tasks:
    - name: Install Open vSwitch
      become: true
      package:
        name: openvswitch-switch
        state: present

    - name: Start Open vSwitch
      become: true
      command: /usr/share/openvswitch/scripts/ovs-ctl start
      changed_when: false

    - name: Wait for Open vSwitch database to be ready
      become: true
      command: ovs-vsctl --no-wait show
      register: ovsdb_check
      until: ovsdb_check is success
      retries: "{{ openvswitch_db_ready_timeout }}"
      delay: 1
      changed_when: false

    - name: Configure system-id and hostname
      become: true
      command: >-
        ovs-vsctl set Open_vSwitch . external_ids:system-id="{{ ansible_facts.hostname }}" external_ids:hostname="{{ ansible_facts.fqdn }}"
      changed_when: false
