---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    openvswitch_db_ready_timeout: 45
  tasks:
    - name: Install Open vSwitch
      become: true
      package:
        name: openvswitch-switch
        state: present

    - name: Start Open vSwitch
      become: true
      command: /usr/share/openvswitch/scripts/ovs-ctl start
      changed_when: false

    - name: Wait for Open vSwitch database socket
      become: true
      wait_for:
        path: /var/run/openvswitch/db.sock
        state: started
        timeout: "{{ openvswitch_db_ready_timeout }}"
      changed_when: false

    - name: Configure system-id and hostname
      become: true
      command: >-
        ovs-vsctl set Open_vSwitch . external_ids:system-id="$(hostname)" external_ids:hostname="$(hostname --fqdn)"
      changed_when: false
