---
- name: Ensuring collectd config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ collectd_user }}"
    group: "{{ collectd_group }}"
    mode: "0770"
  become: true
  with_dict: "{{ collectd_services | select_services_enabled_and_mapped_to_host }}"

- name: Get collectd uid
  become: true
  command: "{{ kolla_container_engine }} run --rm {{ collectd_image_full }} id -u collectd"
  register: collectd_uid_result
  changed_when: false

- name: Get collectd gid
  become: true
  command: "{{ kolla_container_engine }} run --rm {{ collectd_image_full }} id -g collectd"
  register: collectd_gid_result
  changed_when: false

- name: Set collectd uid and gid facts
  set_fact:
    collectd_uid: "{{ collectd_uid_result.stdout }}"
    collectd_gid: "{{ collectd_gid_result.stdout }}"

- name: Ensuring Plugin directory exist
  file:
    path: "{{ node_config_directory }}/collectd/collectd.conf.d"
    state: "directory"
    owner: "{{ collectd_uid }}"
    group: "{{ collectd_gid }}"
    mode: "0755"
  become: true

- name: Copying over custom collectd plugin configuration
  vars:
    service: "{{ collectd_services['collectd'] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/collectd/collectd.conf.d/"
    owner: "{{ collectd_uid }}"
    group: "{{ collectd_gid }}"
    mode: "0660"
  become: true
  when: service | service_enabled_and_mapped_to_host
  with_fileglob:
    - "{{ node_custom_config }}/collectd/collectd.conf.d/*.conf"
    - "{{ node_custom_config }}/collectd/{{ inventory_hostname }}/collectd.conf.d/*.conf"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    owner: "{{ collectd_user }}"
    group: "{{ collectd_group }}"
    mode: "0660"
  become: true
  with_dict: "{{ collectd_services | select_services_enabled_and_mapped_to_host }}"

- name: Copying over collectd.conf for services
  vars:
    service: "{{ collectd_services['collectd'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/collectd/collectd.conf"
    owner: "{{ collectd_user }}"
    group: "{{ collectd_group }}"
    mode: "0660"
  become: true
  with_first_found:
    - "{{ node_custom_config }}/collectd/{{ inventory_hostname }}/collectd.conf"
    - "{{ node_custom_config }}/collectd/collectd.conf"
    - "{{ node_custom_config }}/collectd.conf"
    - "collectd.conf.j2"
  when: service | service_enabled_and_mapped_to_host

- name: Ensuring collectd config directory has correct owner and permission
  file:
    path: "{{ node_config_directory }}/collectd"
    recurse: yes
    owner: "{{ collectd_uid }}"
    group: "{{ collectd_gid }}"
  become: true
