---
- import_playbook: gather-facts.yml

- name: Distribute service secrets
  hosts: all
  serial: '{{ kolla_serial|default("0") }}'
  gather_facts: false
  max_fail_percentage: >-
    {{ secrets_max_fail_percentage | default(kolla_max_fail_percentage) | default(100) }}
  roles:
    - distribute-secrets
