---
- name: Destroying all Kolla containers and volumes
  script: >
    ../tools/cleanup-containers "{{ kolla_container_engine }}"
    {{ '--force' if not destroy_containers_running_vms_fatal | bool else '' }}
