dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/playbook.yml
    verify: ${MOLECULE_SCENARIO_DIRECTORY}/verify.yml
scenario:
  test_sequence:
    - converge
    - idempotence
    - verify
